### ISSUE TITLE
Add support to synthetic alert creation using JSON payload (parameter --from-json)

### ISSUE THREAD

**Issue by DenisMedeiros** [instana/synthetic-synctl#91]
Hi team,

Is it possible to add the feature to allow the creation of alerts using a JSON file, similar to how we can do to create tests?

For example, the command below works:

```bash
synctl create test --type 0 --from-json monitor.json
```

Where my `monitor.json` is defined as below (this JSON content was exported by running `synctl get test <id> --show-json`):

```json
{
  "label": "endpoint",
  "description": "Test",
  "active": true,
  "testFrequency": 5,
  "playbackMode": "Simultaneous",
  "locations": [
    "AAAAAAAAAAAAAAAAAAAA"
  ],
  "locationLabels": [
    "example"
  ],
  "locationDisplayLabels": [
    "us-east-1(NVirginia)"
  ],
  "configuration": {
    "syntheticType": "HTTPAction",
    "markSyntheticCall": true,
    "retries": 0,
    "retryInterval": 1,
    "timeout": "30s",
    "url": "https://example.com",
    "operation": "GET",
    "body": "",
    "validationString": "",
    "followRedirect": true,
    "allowInsecure": true
  },
  "customProperties": {}
}
```

We would like to run something like `synctl create alert --from-json alert.json` (we already can export the alert JSON representation using `synctl get alert <id> --show-json`).

Thanks!

**Comment by swethalohith2** [comment]
Hi Denis,
this feature has been added to the tool. Please upgrade to the latest version, and you can use the command `synctl create alert --from-json alert.json`  to create an alert.

**Comment by rongzhus** [comment]
Added since version v1.1.3, and use `-f` instead of `--from-json` from v2.0.0.
